/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/data/token_indexers/token_characters_indexer.py:56: UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder.
  UserWarning)
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/abajaj/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/abajaj/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/run.py", line 21, in <module>
    run()
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/training/trainer_pieces.py", line 42, in from_params
    all_datasets = training_util.datasets_from_params(params, cache_directory, cache_prefix)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/training/util.py", line 178, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 134, in read
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 134, in <listcomp>
    instances = [instance for instance in Tqdm.tqdm(instances)]
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1108, in __iter__
    for obj in iterable:
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/data/dataset_readers/sequence_tagging.py", line 52, in _read
    file_path = cached_path(file_path)
  File "/home/abajaj/anaconda3/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 106, in cached_path
    raise FileNotFoundError("file {} not found".format(url_or_filename))
FileNotFoundError: file data/only_phrases/multicopy.train.75k.txt not found
0it [00:00, ?it/s]

